# Generated by Django 3.0.5 on 2020-07-09 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Ingrese sus nombre', max_length=40)),
                ('apellidos', models.CharField(help_text='Ingrese sus apellidos', max_length=40)),
                ('cedula', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiante.Estudiante')),
            ],
            options={
                'verbose_name_plural': 'Profesores',
            },
        ),
    ]
