# Generated by Django 3.0.5 on 2020-07-09 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0002_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='apellidos',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombres',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellidos',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombres',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='EstudianteXProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiante.Estudiante')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiante.Profesor')),
            ],
        ),
    ]
