# Generated by Django 3.0.5 on 2020-07-10 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0003_auto_20200709_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='martriculado',
            field=models.DateField(auto_now=True),
        ),
    ]
